In [1]:
# Step 1: Install NumPy into the current Jupyter environment
# (This ensures it works even if your Anaconda environment is different)
import sys
!{sys.executable} -m pip install numpy --quiet

# Step 2: Import NumPy
import numpy as np

# Step 3: Create arrays

# Array from Python list
list_array = np.array([1, 2, 3, 4, 5])

# Array using built-in functions
zeros_array = np.zeros((2, 3))       # 2x3 array filled with zeros
ones_array = np.ones((3, 2))         # 3x2 array filled with ones
range_array = np.arange(0, 10, 2)    # Numbers from 0 to 8 with step 2
linspace_array = np.linspace(0, 1, 5) # 5 numbers between 0 and 1

# Step 4: Display arrays and attributes
def show_array_info(name, arr):
    print(f"\n{name}:")
    print(arr)
    print("Shape:", arr.shape)
    print("Data type:", arr.dtype)
    print("Size:", arr.size)
    print("Number of dimensions:", arr.ndim)

show_array_info("Array from list", list_array)
show_array_info("Zeros array", zeros_array)
show_array_info("Ones array", ones_array)
show_array_info("Range array", range_array)
show_array_info("Linspace array", linspace_array)



Array from list:
[1 2 3 4 5]
Shape: (5,)
Data type: int64
Size: 5
Number of dimensions: 1

Zeros array:
[[0. 0. 0.]
 [0. 0. 0.]]
Shape: (2, 3)
Data type: float64
Size: 6
Number of dimensions: 2

Ones array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Shape: (3, 2)
Data type: float64
Size: 6
Number of dimensions: 2

Range array:
[0 2 4 6 8]
Shape: (5,)
Data type: int64
Size: 5
Number of dimensions: 1

Linspace array:
[0.   0.25 0.5  0.75 1.  ]
Shape: (5,)
Data type: float64
Size: 5
Number of dimensions: 1
