In [1]:
import numpy as np

# Step 1: Create a NumPy array
arr = np.arange(1, 13)  # Array from 1 to 12
print("Original Array (1D):\n", arr)

# Step 2: Reshape into a 3x4 array
reshaped_arr = arr.reshape(3, 4)
print("\nReshaped Array (3x4):\n", reshaped_arr)

# Step 3: Transpose the reshaped array
transposed_arr = reshaped_arr.T
print("\nTranspose of the Reshaped Array (4x3):\n", transposed_arr)

# Step 4: Swap axes (swap axis 0 with axis 1)
swapped_axes_arr = np.swapaxes(reshaped_arr, 0, 1)
print("\nArray after Swapping Axes 0 and 1:\n", swapped_axes_arr)

# Step 5: Swap axes in a 3D example for demonstration
arr_3d = np.arange(24).reshape(2, 3, 4)
print("\nOriginal 3D Array (2x3x4):\n", arr_3d)

swapped_3d = np.swapaxes(arr_3d, 0, 2)
print("\n3D Array after Swapping Axes 0 and 2 (4x3x2):\n", swapped_3d)


Original Array (1D):
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transpose of the Reshaped Array (4x3):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Array after Swapping Axes 0 and 1:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

Original 3D Array (2x3x4):
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

3D Array after Swapping Axes 0 and 2 (4x3x2):
 [[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
